In [1]:
import numpy as np

In [2]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9]],np.int8)

In [3]:
myarr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [4]:
print(myarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
myarr[1,2]

6

In [6]:
myarr[0,0]

1

In [7]:
myarr[1]=[6,5,4]

In [8]:
myarr

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]], dtype=int8)

In [9]:
myarr.shape


(3, 3)

In [10]:
myarr.dtype



dtype('int8')

In [21]:
list1=[1,2,3,4,5,6,7,8,9]

In [22]:
myarr=np.array(list1,np.int8)

In [13]:
myarr

array({1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [14]:
print(myarr)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [15]:
myarr

array({1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [16]:
myarr.size

1

In [17]:
myarr.shape

()

In [18]:
myarr.dtype


dtype('O')

In [23]:
myarr[3]=50

In [24]:
myarr

array([ 1,  2,  3, 50,  5,  6,  7,  8,  9], dtype=int8)

In [26]:
print(myarr[3])

50


In [27]:
myarr[3]

50

In [31]:
zero = np.zeros((2,5))

In [32]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
zero.size

10

In [34]:
zero.shape

(2, 5)

In [36]:
zero.dtype

dtype('float64')

In [37]:
rng = np.arange(12)

In [38]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
rng.shape

(12,)

In [40]:
rng.dtype

dtype('int32')

In [41]:
rng.size

12

In [56]:
ins = np.linspace(1,10,5)

In [57]:
ins

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [58]:
ins.shape

(5,)

In [59]:
ins.size

5

In [60]:
ins.dtype

dtype('float64')

In [63]:
emt=np.empty(50)

In [64]:
emt

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 6.95296598e-310,
       2.27270197e-322, 1.02988961e-311, 1.02988961e-311, 1.02988961e-311,
       1.02988961e-311, 1.02988961e-311, 1.02988961e-311, 1.02988961e-311,
       1.02988961e-311, 1.02988961e-311, 1.02988961e-311, 1.02988961e-311,
       1.02988961e-311, 1.02988961e-311, 1.02988961e-311, 1.02988961e-311,
       1.02988961e-311, 1.02988961e-311, 1.02988961e-311, 1.02988961e-311,
       1.02988961e-311, 1.02988961e-311, 1.02988961e-311, 1.02988961e-311,
       1.02988961e-311, 1.02988961e-311, 1.02988961e-311, 1.02988961e-311,
       1.02988961e-311, 1.02988961e-311, 1.02988962e-311, 1.02988962e-311,
       1.02988962e-311, 1.02988962e-311, 1.02988962e-311, 1.02988962e-311,
       1.02988962e-311, 1.02988962e-311, 1.02988962e-311, 1.02988962e-311,
       1.02988962e-311, 1.02988962e-311, 1.02988962e-311, 1.02988962e-311,
       1.02988962e-311, 1.02988962e-311])

In [65]:
emt.shape

(50,)

In [66]:
emt.dtype

dtype('float64')

In [67]:
arra=np.arange(12)

In [68]:
arra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
aarr=arra.reshape((3,4))

In [72]:
aarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
ara=aarr.ravel()

In [75]:
ara

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
aarr.shape

(3, 4)

In [80]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [81]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
ar.flat

In [84]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [85]:
ar.sum()

45

In [86]:
ar.sum(axis=0)

array([12, 15, 18])

In [87]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [88]:
ar.ndim

2

In [89]:
ar.dtype

dtype('int32')

In [90]:
ar.nbytes

36

In [91]:
one=np.array([1,4,2,3,5,8,7,9,6])

In [92]:
one.size

9

In [93]:
one.argmax()

7

In [95]:
one.argsort()

array([0, 2, 3, 1, 4, 8, 6, 5, 7], dtype=int64)

In [101]:
two=one.reshape((3,3))

In [102]:
two

array([[1, 4, 2],
       [3, 5, 8],
       [7, 9, 6]])

In [103]:
two.argsort()

array([[0, 2, 1],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [104]:
two.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]], dtype=int64)

In [105]:
two.argsort(axis=1)

array([[0, 2, 1],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [106]:
two.argmin()

0

In [108]:
two.argmax()

7

In [109]:
three=two.ravel()

In [110]:
three

array([1, 4, 2, 3, 5, 8, 7, 9, 6])